# Generated by Django 5.2.1 on 2025-05-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_editora_cidade_editora_email_alter_autor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
